import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { X, Sparkles, LogIn, Key, HelpCircle } from 'lucide-react';
import { Group, Member } from '../types';
import { AVATAR_COLORS } from './MemberBalances';

interface JoinGroupModalProps {
  isOpen: boolean;
  onClose: () => void;
  onJoinGroup: (code: string) => void;
  triggerToast: (msg: string) => void;
}

export default function JoinGroupModal({ isOpen, onClose, onJoinGroup, triggerToast }: JoinGroupModalProps) {
  const [codeValue, setCodeValue] = useState('');
  const [errorMsg, setErrorMsg] = useState('');

  if (!isOpen) return null;

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const cleanCode = codeValue.trim().toUpperCase().replace(/\s+/g, '');

    if (cleanCode.length < 5) {
      setErrorMsg('Please enter a 5 or 6-digit alphanumeric code.');
      return;
    }

    onJoinGroup(cleanCode);
    setCodeValue('');
    setErrorMsg('');
    onClose();
  };

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    let value = e.target.value.toUpperCase();
    
    // Automatically insert space in the middle for a 6 digit code for better layout if they don't type a space
    // Let's keep it clean: replace non-alphanumeric chars with empty, max length 7 (6 chars + 1 space)
    const sanitized = value.replace(/[^A-Z0-9]/g, '');
    let formatted = sanitized;
    if (sanitized.length > 3) {
      formatted = `${sanitized.slice(0, 3)} ${sanitized.slice(3, 6)}`;
    }
    
    setCodeValue(formatted);
    if (errorMsg) setErrorMsg('');
  };

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
        {/* Backdrop overlay */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          onClick={onClose}
          className="fixed inset-0 bg-slate-900/60 dark:bg-black/80 backdrop-blur-xs"
        />

        {/* Modal body sheet */}
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 15 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 15 }}
          transition={{ type: 'spring', duration: 0.4 }}
          className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-3xl p-6 shadow-2xl max-w-sm w-full relative z-10 overflow-hidden"
          id="join-group-modal"
        >
          {/* Accent border top decoration */}
          <div className="absolute top-0 left-0 right-0 h-1.5 bg-gradient-to-r from-emerald-500 via-teal-500 to-indigo-500" />

          {/* Close button top-right */}
          <button
            onClick={onClose}
            className="absolute top-4 right-4 p-1.5 rounded-xl hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-400 dark:text-slate-500 hover:text-slate-700 dark:hover:text-slate-300 transition-all cursor-pointer"
            aria-label="Close modal"
          >
            <X size={16} />
          </button>

          {/* Icon Header */}
          <div className="flex items-center gap-3 mb-5 pt-2">
            <span className="w-9 h-9 rounded-xl bg-emerald-50 dark:bg-emerald-950/40 text-emerald-600 dark:text-emerald-400 flex items-center justify-center shadow-xs">
              <LogIn size={16} />
            </span>
            <div>
              <p className="text-[10px] font-black text-slate-400 dark:text-slate-500 uppercase tracking-widest font-mono">
                MEMBERSHIP portal
              </p>
              <h3 className="text-sm font-black text-slate-900 dark:text-white">
                Join Group with Code
              </h3>
            </div>
          </div>

          <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed mb-6">
            Enter the 6-digit invite code generated by your roommate or friend to instantly synchronize group expenses and bank settle profiles.
          </p>

          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="space-y-1.5">
              <label className="block text-[10px] font-bold text-slate-400 uppercase tracking-widest font-mono">
                Enter Invite Code
              </label>

              <div className="relative flex items-center">
                <span className="absolute left-3.5 text-slate-400 dark:text-slate-500">
                  <Key size={14} />
                </span>
                <input
                  type="text"
                  maxLength={7}
                  placeholder="e.g. ROOM3A or 784 102"
                  value={codeValue}
                  onChange={handleInputChange}
                  className="w-full pl-10 pr-4 py-3 bg-slate-50 dark:bg-slate-805 border-none rounded-xl text-center text-sm font-black font-mono tracking-widest text-slate-800 dark:text-white focus:ring-2 focus:ring-emerald-500/20 uppercase"
                  autoFocus
                  required
                  id="input-join-group-code"
                />
              </div>

              {errorMsg && (
                <p className="text-[10px] text-red-500 font-semibold mt-1">
                  ⚠️ {errorMsg}
                </p>
              )}
            </div>

            {/* Simulated Hint */}
            <div className="bg-slate-50/55 dark:bg-slate-805/20 rounded-xl p-3 border border-slate-100 dark:border-slate-850 flex gap-2.5 items-start">
              <span className="text-slate-400 text-xs shrink-0 mt-0.5"><HelpCircle size={13} /></span>
              <p className="text-[10px] text-slate-400 leading-normal">
                Want to try? Enter <strong className="text-emerald-500 dark:text-emerald-400">ROOM3A</strong> to instantly launch the mock <strong>Apartment 3A Roomies</strong> split group!
              </p>
            </div>

            <button
              type="submit"
              className="w-full mt-2 py-3 bg-indigo-600 hover:bg-indigo-700 active:scale-[0.98] text-white rounded-xl text-xs font-bold transition-all flex items-center justify-center gap-1.5 cursor-pointer shadow-md shadow-indigo-100 dark:shadow-none"
              id="btn-confirm-join-group"
            >
              <Sparkles size={12} className="text-indigo-200" />
              <span>Join Group instantly</span>
            </button>
          </form>
        </motion.div>
      </div>
    </AnimatePresence>
  );
}
